#!/bin/sh
find /tmp/mm6.r2/ -type f -name \*.php | while read file; do iconv -f ISO-8859-1 -t UTF-8 < "$file" > "$file-utf8"; done
find /tmp/mm6.r2/ -type f -name \*.tpl | while read file; do iconv -f ISO-8859-1 -t UTF-8 < "$file" > "$file-utf8"; done
find /tmp/mm6.r2/ -type f -name \*.js | while read file; do iconv -f ISO-8859-1 -t UTF-8 < "$file" > "$file-utf8"; done
find /tmp/mm6.r2/ -type f -name \*.css | while read file; do iconv -f ISO-8859-1 -t UTF-8 < "$file" > "$file-utf8"; done
