tinyMCE.init({
	mode : "textareas",
	theme : "advanced",
	theme_advanced_buttons1 : "bold, italic, underline, forecolor, fontsizeselect, |, strikethrough, blockquote, undo, redo, |, link, unlink, image, emotions, code",
	theme_advanced_buttons2 : "",
	theme_advanced_buttons3 : "",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	theme_advanced_statusbar_location : "bottom",
    theme_advanced_resizing : true,
    theme_advanced_resize_horizontal : false,
    forced_root_block : false,
	force_br_newlines : true,
	force_p_newlines : false,    
	convert_newlines_to_brs : true,
	remove_linebreaks : false,
	apply_source_formatting : true,
	convert_fonts_to_spans : false,
	entity_encoding : "raw",
	plugins : "bbcode, emotions",
	language : '<tag:lang />',
	theme_advanced_buttons3_add : "fullpage"
});