INSERT INTO countries (country, isocode) VALUES ("Shqipëria", "AL");
INSERT INTO countries (country, isocode) VALUES ("Andorra", "AD");
INSERT INTO countries (country, isocode) VALUES ("Österreich", "AT");
INSERT INTO countries (country, isocode) VALUES ("آذربايجان", "AZ");
INSERT INTO countries (country, isocode) VALUES ("Беларусь", "BY");
INSERT INTO countries (country, isocode) VALUES ("België", "BE");
INSERT INTO countries (country, isocode) VALUES ("Bosna i Hercegovina", "BA");
INSERT INTO countries (country, isocode) VALUES ("България", "BG");
INSERT INTO countries (country, isocode) VALUES ("Hrvatska", "HR");
INSERT INTO countries (country, isocode) VALUES ("Κύπρος", "CY");
INSERT INTO countries (country, isocode) VALUES ("Česká republika", "CZ");
INSERT INTO countries (country, isocode) VALUES ("Danmark", "DK");
INSERT INTO countries (country, isocode) VALUES ("Eesti", "EE");
INSERT INTO countries (country, isocode) VALUES ("Føroyar", "FO");
INSERT INTO countries (country, isocode) VALUES ("Suomi", "FI");
INSERT INTO countries (country, isocode) VALUES ("France", "FR");
INSERT INTO countries (country, isocode) VALUES ("Deutschland", "DE");
INSERT INTO countries (country, isocode) VALUES ("Ελλάδα", "GR");
INSERT INTO countries (country, isocode) VALUES ("Guernsey", "GG");
INSERT INTO countries (country, isocode) VALUES ("Magyarország", "HU");
INSERT INTO countries (country, isocode) VALUES ("Ísland", "IS");
INSERT INTO countries (country, isocode) VALUES ("Ireland", "IE");
INSERT INTO countries (country, isocode) VALUES ("Isle of Man", "IM");
INSERT INTO countries (country, isocode) VALUES ("Italia", "IT");
INSERT INTO countries (country, isocode) VALUES ("Jersey", "JE");
INSERT INTO countries (country, isocode) VALUES ("Latvija", "LV");
INSERT INTO countries (country, isocode) VALUES ("Liechtenstein", "LI");
INSERT INTO countries (country, isocode) VALUES ("Lietuva", "LT");
INSERT INTO countries (country, isocode) VALUES ("Luxembourg", "LU");
INSERT INTO countries (country, isocode) VALUES ("Македонија", "MK");
INSERT INTO countries (country, isocode) VALUES ("Malta", "MT");
INSERT INTO countries (country, isocode) VALUES ("Молдова", "MD");
INSERT INTO countries (country, isocode) VALUES ("Monaco", "MC");
INSERT INTO countries (country, isocode) VALUES ("Црна Гора", "ME");
INSERT INTO countries (country, isocode) VALUES ("Nederland", "NL");
INSERT INTO countries (country, isocode) VALUES ("Norge", "NO");
INSERT INTO countries (country, isocode) VALUES ("Polska", "PL");
INSERT INTO countries (country, isocode) VALUES ("Portugal", "PT");
INSERT INTO countries (country, isocode) VALUES ("România", "RO");
INSERT INTO countries (country, isocode) VALUES ("Россия", "RU");
INSERT INTO countries (country, isocode) VALUES ("San Marino", "SM");
INSERT INTO countries (country, isocode) VALUES ("Србија", "RS");
INSERT INTO countries (country, isocode) VALUES ("Slovensko", "SK");
INSERT INTO countries (country, isocode) VALUES ("Slovenija", "SI");
INSERT INTO countries (country, isocode) VALUES ("España", "ES");
INSERT INTO countries (country, isocode) VALUES ("Sverige", "SE");
INSERT INTO countries (country, isocode) VALUES ("Schweiz", "CH");
INSERT INTO countries (country, isocode) VALUES ("Türkiye", "TR");
INSERT INTO countries (country, isocode) VALUES ("United Kingdom", "UK");
INSERT INTO countries (country, isocode) VALUES ("Україна", "UA");
INSERT INTO countries (country, isocode) VALUES ("Vaticanum", "VA");
