CREATE TABLE IF NOT EXISTS `n_users` (
uid int(11) NOT NULL auto_increment,
id_level int(10) NOT NULL default '0',
username varchar(32) NOT NULL,
name varchar(8) NOT NULL,
password varchar(40) NOT NULL,
email varchar(100) NOT NULL,
disabled enum('yes', 'no') NOT NULL default 'no',
language tinyint(4) NOT NULL default '0',
country tinyint(4) NOT NULL default '0',
joined datetime NOT NULL default '0000-00-00 00:00:00',
lastconnect datetime NOT NULL default '0000-00-00 00:00:00',
joinipa bigint(11) NOT NULL default '0',
lastipa bigint(11) NOT NULL default '0',
downloaded bigint(20) NOT NULL default '0',
uploaded bigint(20) NOT NULL default '0',
credits int(10) NOT NULL default '0',
downspeed varchar(40) NOT NULL,
upspeed varchar(40) NOT NULL,
isp varchar(40) NOT NULL,
machineon varchar(100) NOT NULL,
sex enum('female', 'male') NOT NULL,
bornyear tinyint(4) NOT NULL,
avatar varchar(155) DEFAULT NULL,
signature varchar(255) DEFAULT NULL,
invites int(10) NOT NULL default '0',
invited_by int(10) NOT NULL default '0',
introduction text,
lastdonate datetime NOT NULL default '0000-00-00 00:00:00',
donatedx tinyint(4) NOT NULL default '0',
can_upload enum('yes', 'no') NOT NULL default 'yes',
can_leech tinyint(4) NOT NULL default '1',
wait_time int(11) NOT NULL default '0',
peers_limit int(11) NOT NULL default '0',
torrents_limit int(11) NOT NULL default '10',
torrent_pass varchar(32) NOT NULL,
torrent_pass_secret bigint(20) NOT NULL,
pass blob NOT NULL,
fid_end int(11) NOT NULL,
pid varchar(32) DEFAULT NULL,
  PRIMARY KEY  (`uid`),
  UNIQUE KEY `username` (`username`),
  KEY `email` (`email`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
